enum ContentModelStatus {
  DRAFT
  LIVE
}

type FieldValidations {
  required: Boolean
  unique: Boolean
  minCount: Int
  maxCount: Int
  matchPattern: String
  prohibitPattern: String
  allowedValues: [String!]
}

scalar JSON

type ContentField {
  id: ID!
  name: String!
  type: String!
  apiId: String!
  icon: String!
  localized: Boolean!
  required: Boolean!
  isTitle: Boolean!
  description: String
  validations: JSON
  appearance: JSON
  defaultValue: JSON
  settings: JSON
}

type ContentModel {
  id: ID!
  workspaceId: String
  name: String!
  apiId: String!
  description: String
  icon: String!
  status: ContentModelStatus!
  createdAt: DateTime!
  updatedAt: DateTime!
  createdBy: Int!
  updatedBy: Int
  fields: [ContentField!]!
  creator: User
  updater: User
}

input FieldValidationsInput {
  required: Boolean
  unique: Boolean
  minCount: Int
  maxCount: Int
  matchPattern: String
  prohibitPattern: String
  allowedValues: [String!]
}

input CreateContentFieldInput {
  name: String!
  type: String!
  apiId: String!
  icon: String!
  localized: Boolean
  required: Boolean
  isTitle: Boolean
  description: String
  validations: JSON
  appearance: JSON
  defaultValue: JSON
  settings: JSON
}

input CreateContentModelInput {
  workspaceId: String
  name: String!
  apiId: String!
  description: String
  icon: String!
  fields: [CreateContentFieldInput!]
}

type Query {
  getContentModels: [ContentModel!]!
  getContentModel(id: ID!): ContentModel
  deliveryGetModels: [ContentModel!]!
}

type Mutation {
  createContentModel(input: CreateContentModelInput!): ContentModel!
  updateContentModel(id: ID!, input: CreateContentModelInput!): ContentModel!
  deleteContentModel(id: ID!): Boolean!
}
