type Workspace {
  id: ID!
  name: String!
  description: String
  types: Int!
  env: Int!
  records: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  members: [WorkspaceMember!]!
  _count: WorkspaceCount
}

type WorkspaceCount {
  models: Int
  contents: Int
}

type WorkspaceMember {
  id: ID!
  workspaceId: String!
  userId: Int!
  role: String!
  createdAt: DateTime!
  user: User!
}

input CreateWorkspaceInput {
  name: String!
  description: String
}

type Query {
  getWorkspaces: [Workspace!]!
  getWorkspace(id: ID!): Workspace
}

type Mutation {
  createWorkspace(input: CreateWorkspaceInput!): Workspace!
  updateWorkspace(id: ID!, name: String!): Workspace!
  deleteWorkspace(id: ID!): Boolean!
  inviteMember(workspaceId: ID!, email: String!, role: String!): Boolean!
}
